### ISSUE TITLE
data-live-search problem 

### ISSUE THREAD

**Issue by HengCC** [snapappointments/bootstrap-select#1240]
when  i use "data-live-search=true" and there are many options which some word contains space.
then the problem was occured,because the options is not only contain english word ,but also chinese word. when i  input chinese word , the chinese input method will have an "space" placeholder in the input box until i input an chinese word, then bootstrap-select will search "space" before the word input,  this will cause the input method  coundn't  input any chinese word.

**Comment by livem** [comment]
chrome 下中文输入，进行搜索的时候，被打断的情况么？

**Comment by HengCC** [comment]
是的。在中文输入的时候，使用中文输入法在输入汉字但是并没有录入输入框之前，文本输入框中会出现一个空格，这时候自动搜索就会搜索空格去了，导致后面输入法输入的中文无法输入。就更不能搜索了。

**Comment by julei** [comment]
我这里使用的在Chrome上OK，在Firefox上有问题，搜狗输入法。 
This problem occured when I use firefox (44.0.2), while it doesn't come up in Chrome ( 48.0.2564.116 ). ( Sogou input method )

**Comment by livem** [comment]
`if (that.$searchbox.val()) that.$lis.not('.hidden, .divider, .dropdown-header').eq(0).addClass('active').children('a').focus();`

我把这行代码后面的 focus() 去掉，中文搜索就没问题了。

改为：

`if (that.$searchbox.val()) that.$lis.not('.hidden, .divider, .dropdown-header').eq(0).addClass('active').children('a');`

**Comment by caseyjhol** [comment]
## Bug reports

A bug is a _demonstrable problem_ that is caused by the code in the repository.
Good bug reports are extremely helpful - thank you!

Guidelines for bug reports:

1. **Use the GitHub issue search.** Check if the issue has already been
   reported.

2. **Check if the issue has been fixed.** Try to reproduce it using the
   latest `master` or development branch in the repository.

3. **Provide environment details.** Provide your operating system, browser(s),
   jQuery version, Bootstrap version, and bootstrap-select version.

4. **Create an isolated and reproducible test case.** Create a [reduced test
   case](http://css-tricks.com/6263-reduced-test-cases/).

5. **Include a live example.** Make use of jsFiddle or jsBin to share your
   isolated test cases.

A good bug report shouldn't leave others needing to chase you up for more
information. Please try to be as detailed as possible in your report. What is
your environment? What steps will reproduce the issue? What browser(s) and OS
experience the problem? What would you expect to be the outcome? All these
details will help people to fix any potential bugs.

Example:

> Short and descriptive example bug report title
>
> A summary of the issue and the browser/OS environment in which it occurs. If
> suitable, include the steps required to reproduce the bug.
>
> 1. This is the first step
> 2. This is the second step
> 3. Further steps, etc.
>
> `<url>` - a link to the reduced test case
>
> Any other information you want to share that is relevant to the issue being
> reported. This might include the lines of code that you have identified as
> causing the bug, and potential solutions (and your opinions on their
> merits).
