### ISSUE TITLE
Create dist only bower

### ISSUE THREAD

**Issue by david2tm** [snapappointments/bootstrap-select#1321]
Currently bower includes all the project, whilst it should IMHO ignore the sources and provide only productions ready files, aka dist folder.

**Comment by holtkamp** [comment]
Got the same observation, the following screenshot indicates a big amount of files, compared to another package with a similar structure (`jquery-date-range-picker`)

![screen shot 2017-03-21 at 16 52 45](https://cloud.githubusercontent.com/assets/776405/24156462/e03be04c-0e56-11e7-8cf3-c7e649481c5a.png)

versus

![screen shot 2017-03-21 at 16 52 52](https://cloud.githubusercontent.com/assets/776405/24156471/e4d6bd8e-0e56-11e7-8278-fae0165a55c8.png)

I think an `ignore` section in `bower.json` already does the job, [for example like this](https://github.com/longbill/jquery-date-range-picker/blob/1a060b712f2f71ba9403b85c998d13bc315769a9/bower.json#L29-L38)

**Comment by markus-s24** [comment]
This causes Spring's WebJar integration to fail (MultipleMatchesException), if the version number is not included in the url. This is because bootstrap-select.js etc. is included twice:
* dist/js/bootstrap-select.js
* docs/docs/dist/js/bootstrap-select.js (should not be included)

Please fix this, thanks.

**Comment by caseyjhol** [comment]
Released in [v1.13.6](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.6)!
