### ISSUE TITLE
Multiple Select Width Wider than Container

### ISSUE THREAD

**Issue by stap123** [snapappointments/bootstrap-select#1343]
I'm having an issue with using this (the multiple select version) within a table cell set to col-sm-6.

When the selected items are comma separated (within the button at the top level when it's collapsed) if the list is wider than the contents of the container the whole display does something strange, it makes the width as wide as the items all the time (ignoring the container size).

This is the standard display as expected with only 2 items selected.
![image](https://cloud.githubusercontent.com/assets/10199083/14067044/2de4959c-f453-11e5-92c7-7fafe4c532d4.png)

But if I select 4 for example it does as below, and this continues to get wider and wider as more are selected
![image](https://cloud.githubusercontent.com/assets/10199083/14067046/59f0dd9e-f453-11e5-860d-def653d571bd.png)

Someone will probably tell me a really simple css fix for this but I can't claim to be an expert in css so any help is muchly appreciated.

Can anyone offer any guidance?

P.s. Sorry if this is incorrectly formatted in any way, I've never raised an error on here before.

**Comment by ikr0m** [comment]
This should help: 
`.bootstrap-select.btn-group .dropdown-toggle .filter-option {
    white-space: normal;
}`

**Comment by shehi** [comment]
I can confirm the issue. Whenever ```width: auto``` is set, the calculated width is way larger than the width of the container. Thing is, when CTRL+F5'ed, the calculated width is correct. When F5'ed, it is not ( @stap123 : can you confirm this behavior as well?).

@ikr0m 's solution doesn't work.

**Comment by guhweb** [comment]
Hi, i solved with

```
.bootstrap-select:not([class*="col-"]):not([class*="form-control"]):not(.input-group-btn){
    width:100%;
}
```
Thats works fine :)

Source: https://stackoverflow.com/questions/39177989/bootstrap-multiselect-dropdown-width-100

**Comment by jonathanhaglund** [comment]
When I set data-width="100%" I get the issue reported (the calculated width is the full width of the screen). The fix for me is `.dropdown-menu.open{width:100%}`.

In my case, the behavior is caused by the virtualScroll option. When I have more elements than the specified or default value, this issue happens. If I raise the value to something very large, its fine without the CSS directive.

The selects are all `class="form-control"` and contained within rows/columns. Same behavior when the containers are a form with `class="form-horizontal"` and form-group instead of rows.

chrome 78.0.3904.97
jquery 3.4.1
bootstrap 3.4.1
bootstrap-select 1.13.11
