### ISSUE TITLE
Button to Deselect the selected value ?

### ISSUE THREAD

**Issue by amitsquare** [snapappointments/bootstrap-select#1449]
As per documentation , **"data-action-box"** adds the two button to select all / deselect all button in the header .But this only happens in case of "multiple selection " .

Is there any way to add similar deselect button for single selection dropdown ?

**Comment by caseyjhol** [comment]
No - I recommend using a multiple select with `data-max-options="1"`.

**Comment by amitsquare** [comment]
But this is not correct solution , As **selectAll** button will select all the options .

**Comment by tontonsb** [comment]
I also need a dropdown where you can select an option or select none of them. Currently this requires using multiple, otherwise the user can't deselect. Or we have to introduce the action bar which allows the users to deselectAll and selectAll.

But how do we get value out of this? Currently I have to do this, to get the single value out of multiple-select element:

`elementVal = element.val() ? element.val()[0] : null;`

Of course, this is all doable, but it shouldn't require so many workarounds to do these things.

It also would be useful if we could include only the deselectAll button without the selectAll :)

**Comment by puneet97** [comment]
+1 for Deselect/Clear button for single selection dropdown.
Using a multiple select adds a redundant **Select All** button and the **Deselect _All_** button doesn't look correct as we're allowing selection/deselection of only _one_ option.

**Comment by ernestopinchaaqui** [comment]
+1 for Desect/Clear

**Comment by mattfeury** [comment]
+1

**Comment by szmalec** [comment]
+1

**Comment by zsoltiNagy** [comment]
+1

**Comment by keymastervn** [comment]
+1

**Comment by sohebcakewalk** [comment]
+1 for Desect/Clear

**Comment by jadamec** [comment]
+1

**Comment by florianbinderme** [comment]
+1

**Comment by mulite** [comment]
+1

**Comment by fr0z3nfyr** [comment]
+1

**Comment by maurizioPollen** [comment]
+1

**Comment by tombauto** [comment]
3 years after and this isn't a feature up until now?
I wonder why, as I am new on using this tool and I really like what you have done here.
But this feature is actually expected as we are improving the way traditional selection works, rather than a user adding an option "~none~" as another selection, as Clear/Deselect is the perfect way to do it.

I tried to insert an element during ready but not all time the element gets inserted, maybe because the generator for selectpicker() was not done yet; However there is no .done() function to extend to selectpicker, so my workwaround was to put this insert to a setTimeout but it feels more a hack rather than proper integration. I also don't get the same result every time, not all the time the element gets inserted even it is a delayed time.

Here is my code for adding element:

$(function(){
		$(".selectpicker").find("ul").append('<li><div class="dropdown-item"><button class="btn btn-default w-100" type="button" onClick="clearSelectionDropDown(this);">Clear Selection</button></div></li>');
});

Although the above code, may work on adding the element, I couldn't make the clear function work.
I was only able to clear the current selected option, but when selecting another value, its no longer reflecting as selected.

[EDIT] : I was able to do a work-around but still require setTimeout but for this approach I followed the suggested using of "multiple" with data-max-options="1"
Here is the code:

            setTimeout(function () {
                enableClearOptionInSelect("opt-mySelection");
            }, 1000);

        let enableClearOptionInSelect = function (id) {
            $("#"+ id +" .bs-select-all").hide(); // Hide Select-All
            let btnClear = $("#"+ id +" .bs-deselect-all");
            btnClear.html("Clear Selection");
            btnClear.addClass("w-100");
            console.log("enableClearOptionInSelect completed.");
        }

Output:
![image](https://user-images.githubusercontent.com/2554887/65145468-3b5f9400-da4c-11e9-8128-b666a7b88d85.png)

**Comment by hartadi** [comment]
+1 pls

**Comment by caseyjhol** [comment]
This change will be a part of the v1.14.0 release. This issue will be updated after it's made available. 

### How to enable
`allowClear: true` or `data-allow-clear="true"`

Demos:
- Bootstrap 4: https://plnkr.co/edit/c2XDSXipVnbMkjaM
- Bootstrap 3: https://plnkr.co/edit/2OcOGhfmBxRpbDh2

**Comment by ctf0** [comment]
until the new option is released, u can use the below to target the select with single option only
```scss
.bootstrap-select {
    select[data-max-options='1'] ~ .dropdown-menu .bs-actionsbox {
        display: none;
    }
}
```

now u have the same behavior as multi selection, keep in mind that this will not auto focus the selected option when the menu opens 👎 .

**PS**
there is also https://codepen.io/Prateik2710/pen/vpgKdL

**PPS**
you can also add an empty option to the start of your list.

**Comment by caseyjhol** [comment]
Released in [v1.14.0-beta](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.14.0-beta)!

**Comment by scammi** [comment]
Until allowClear function well is tested.

![Screenshot_2021-04-12_17-17-19](https://user-images.githubusercontent.com/40045101/114456429-3b396300-9bb3-11eb-913f-d0b3043b80bf.png)

https://codepen.io/scammi/pen/XWpErrL

**Comment by MaaxGr** [comment]
3 years and 1.14 is still not released. :o

I used input-groups for now to solve this problem:
```
<div class="form-group">
    <label for="unternehmen_Ansprechpartner_Intern">Ansprechpartner intern:</label>
    <div class="input-group">
        <select id="unternehmen_Ansprechpartner_Intern"
                name="unternehmen_Ansprechpartner_Intern"
                class="form-control selectpicker"
                data-live-search="true" data-non-selected-text="body" data-allow-clear="true">
            <option value=""></option>
            <option value="1">Großmann, Max</option>
        </select>
        <span class="input-group-addon" id="basic-addon2"
              style="cursor: pointer"
              onclick="$('select[name=unternehmen_Ansprechpartner_Intern]').selectpicker('val', '')">
            <i class="fas fa-times"></i>
        </span>
    </div>
</div>
```

![image](https://github.com/snapappointments/bootstrap-select/assets/43404580/638be0fa-24fa-48fd-9679-3ca124c7761a)
