### ISSUE TITLE
Odd character (null) in bootstrap-select.less

### ISSUE THREAD

**Issue by PhilPJL** [snapappointments/bootstrap-select#1546]
Question:

Resharper isn't happy with the \0 below.  Should it be there, and if so why?

https://github.com/silviomoreto/bootstrap-select/blob/master/less/bootstrap-select.less
...
.bootstrap-select { 
   width: 220px \0; /*IE9 and below*/

**Comment by jkrehm** [comment]
Looking at the git history, my bet is that once upon a time it was `\9` because IE8 and below doesn't support `:not()`. The width is set via a rule that contains `:not()` so this was a [fallback for IE8](http://stackoverflow.com/a/8004962/719817).

According to [caniuse.com](http://caniuse.com/#feat=css-sel3), IE9+ supports `:not()` so it was never required for IE9. Therefore I think it can be removed, but haven't tried it to make sure the width is still set correctly.

**Comment by NicolasCARPi** [comment]
See: https://github.com/snapappointments/bootstrap-select/issues/1122
