### ISSUE TITLE
I can't Receive values from select options in php .. it returns null . but i have to receive options values

### ISSUE THREAD

**Issue by arifsajal70** [snapappointments/bootstrap-select#1565]
i give name on select tag . and make a foreach loop to get options from database .. i need the values from the options .. when i submit the form it returns null . please help me on this matter .

**Comment by caseyjhol** [comment]
Does it work without bootstrap-select? Are you using a PHP framework?

**Comment by zeroun01** [comment]
Hi,
I have the same problem.
I'm using bootstrap-select 1.12.1 in symfony3.1 framework.
When I submit the form containing a simple bootstrap-select field, all fields are submitted in http request except  bootstrap-select one.

**Comment by arifsajal70** [comment]
yes . codeigniter framework .

**Comment by robertbarros** [comment]
I am having this issue too. BUT, I am using plain php no frame work at all. if you click to open the dropdown and start typing and click on the option that satisfy your search it works just fine BUT if you open the dropdown and by any chance your option is right there without to have scrolldown and you selected it with mouse no value is passed to the selected option and php is considering Null. Since I am not that great in .js I will have to put this on hold. But if you have presence this issue and have fixed please let me know!
