### ISSUE TITLE
Webpack configuration issues - Bootstrap-select with Angular 2.4.8

### ISSUE THREAD

**Issue by AngularTx** [snapappointments/bootstrap-select#1670]
I wanted to use the Bootstrap-select package in my application. I have some challenges in getting the application work . 

Using Webpack with Angular 2.4.8 version.  The appearance is not getting changed. The only thing happens is that the select drop down is hidden . No other changes can be seen. Could be issues with the Webpack Configuration. Can some one help here .

**Comment by robertbarros** [comment]
Just for the records. The following issue happened with my in the very beginning when setting up the Selectpick. I figured out that the problem was nothing more than adjustament position on my CSS. Make sure have your div set with position: relative, z-index: ??

... not sure if going to work for your that I thought would be a good idea to drop that! good luck!

**Comment by AngularTx** [comment]
Hi @robertbarros 

Thanks for the reply. Can you provide me the sample which worked for you ? 
Is it possible for you to provide the webpack configuration  ?

**Comment by urbanhusky** [comment]
Did you initialise all `selectpicker` elements?
If you're not dynamically adding `select`s to the DOM (i.e. `*ngIf` etc.), then you could initialise all bootstrap-select `select`s like so:

```
    ngAfterViewInit() {
        $(".selectpicker").selectpicker();
    }
```

*Note: I'm using webpack and `ProvidePlugin` to map `jQuery` to `$`*

**However** this will not work if you're adding or removing bootstrap-select elements at runtime. This is because bootstrap-select hides all `<select>` elements via CSS and adds its own html to render its dropdown (via JS).
So if, for example, a `*ngIf` toggles a `<select class="selectpicker">`, then it will be invisible once the `*ngIf` evaluates to true (except if that's the initial state) - because the code to turn all `selectpicker`s into bootstrap-selects is only run after all child views were initialised, not after bindings are updated.

I'd be hesitant to call the `$(".selectpicker").selectpicker();` on every potential change. I would fully expect this to have a major impact on performance - and I'm not sure if you could simply execute that code subsequently on `<select>`s that are already turned into bootstrap-selects.
