### ISSUE TITLE
Bootstrap-select not working in Angular 4 

### ISSUE THREAD

**Issue by ninethug** [snapappointments/bootstrap-select#1806]
Hi,

I tried to make bootstrap-select with angular 4 but it doesn't seem to work. I installed jQuery, bootstrap and then bootstrap-select. Here is a plunkr : https://plnkr.co/edit/Lia1OpL50VnVlJL0MBVZ?p=preview

**Comment by viniciosyals** [comment]
Same problem here...

**Comment by pwyssmuller** [comment]
yeah same here. It never renders the first time. Once you refresh the page, it will appear. 
Does anyone has a solution?

**Comment by braheem** [comment]
Although ideally you would not have to, I got it working in your plunker by explicitly initializing the select. See this forked plunker: https://plnkr.co/edit/ts4uS8yug4OWyjNEEWPR

If you plan to use bootstrap-select in your Angular app for more than just a very basic use case, you should probably wrap it in a directive.

I've created an example project that demonstrates one way you can wrap bootstrap-select in Angular 4 so that you can use it across your project in an 'Angular' way.
https://github.com/braheem/angular-bootstrap-select

**Comment by pwyssmuller** [comment]
@braheem Hi there, that works great. I was just wondering how you would handle multiple bootstrap select items in the same component? Sorry, very new to Angular...

**Comment by pwyssmuller** [comment]
@braheem Hi there, this works great. However, I was wondering how you would implement multiple bootstrap select dropdown into the same component. Sorry, very new to Angular...
Thanks !

**Comment by braheem** [comment]
@pwyssmuller So I recently updated the linked example project I provided to add another bootstrap-select dropdown to the app component. In my opinion, I think that each instance of a bootstrap-select dropdown should be a component itself, so you'll see that there isn't much to it if you go that route after looking at the project.

However, there may be a use case where you strictly want multiple instances of bootstrap-select in one single component rather than as multiple child components. I'll see if I can add an example for that.. All you need to do to have multiple bootstrap-select dropdowns in the same component is not extend from BaseBootstrapSelect and contain all of your logic in the component you plan to use. It's template will have the multiple select elements with the 'bootstrapSelect' directive specified, and the component itself will have a ViewChild reference to each of them by using an identifier, something like this:

In the component:
`@ViewChild('select1') select1 : BootstrapSelectDirective;` 

In the template:
`<select #select1 bootstrapSelect .... >..</select>`

Repeat for all other instances of bootstrap select that you want in your component. The only problem I have with this is that if each select dropdown is unique in its options, you'll have a lot of code that may be hard to keep track of in the component (all the collections for the different options, the different variables to store selected options for each select etc).

If you have any issues or more questions, feel free to open them on the project I linked.

**Comment by annisadwinidia** [comment]
@braheem  Hi there, this works great. However, I was wondering how to set selected option / value. I need to set selected option for editing form.
Thanks !

**Comment by braheem** [comment]
@annisadwinidia I am assuming you are talking about setting selected option programmatically. The solution should preselect options properly when the selectpicker is loaded. However, after the selectpicker is loaded, if you want to set the selected option without the user interacting with the dropdown, you need to use some jQuery to do so.

It gets tricky because you will also need to manually dispatch a change event to let Angular know of the change to the select that you made using jQuery.

I updated the project with an example that shows you how you can do this. In general you should try to keep all the jQuery in the wrapper directive to keep a clean implementation.

I'd like to stop adding noise to this thread so if anyone has any issues or questions about my example, please open an issue in the project I linked.

**Comment by rockers007** [comment]
@braheem Thank you so much, this works great
