### ISSUE TITLE
Position sticky: page jumps to the top after clicking on select or option (in Chrome)

### ISSUE THREAD

**Issue by OlenaRehush** [snapappointments/bootstrap-select#1950]
I am using select-picker on a toolbar which is in position: sticky.

See the fiddle: [https://jsfiddle.net/Lzz4tm0g/2/](https://jsfiddle.net/Lzz4tm0g/2/)

Steps to reproduce:
 - Scroll a little to page bottom.
 - Click on the select-picker.
Actual result: page scrolls to the top. (Sometimes it reproduces only the first time that you click on select).
 - Scroll again to the bottom.
 - Click on any option.
Actual result: page scrolls to the top again.

**Comment by caseyjhol** [comment]
Released in [v1.13.2](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.2)!

**Comment by theCSSguru** [comment]
This was fixed on the first click for Chrome, but not when an Option is selected, it still jumps to the top of the screen for me when my parent container has position: sticky;

I checked in Firefox and it's not an issue, but for Chrome it is, I wonder if that's because of how Chrome deals with Sticky?

**Comment by caseyjhol** [comment]
@theCSSguru Seems like this has been resolved in Chrome 72 (or earlier)? I can't seem to reproduce it now.
