### ISSUE TITLE
bootstrap-select 1.30.1 and bootstrap 4.1.1 incorrectly show

### ISSUE THREAD

**Issue by xuchenCN** [snapappointments/bootstrap-select#1982]
I'm working with bootstrap-select 1.30.1 and bootstrap 4.1.1
So this coming 
![image](https://user-images.githubusercontent.com/2757089/40968320-df3b78d2-68e7-11e8-8331-fb5f898aed9c.png)
![image](https://user-images.githubusercontent.com/2757089/40968332-e9d0462e-68e7-11e8-91a6-861ba4421989.png)

browser : Google Chrome
os: osx

**Comment by caseyjhol** [comment]
Since v1.13.0, the official repository for bootstrap-select has moved to https://github.com/snapappointments/bootstrap-select. Please report all issues there for the fastest response.

Without additional information, it's difficult to say what the cause of your issue is - it looks like you may not have included the CSS correctly (either for Bootstrap or for Bootstrap-select). Please include a live example so I can further debug.

**Comment by xuchenCN** [comment]
Thanks ! Fixed issue when add <!doctype html>

**Comment by slidenerd** [comment]
Whoaaaaaa what is this issue, I spent an entire day figuring out what was wrong, why is doctype affecting this???
