### ISSUE TITLE
Extra tick mark when using livesearch in Bootstrap 4

### ISSUE THREAD

**Issue by jaredtaskin** [snapappointments/bootstrap-select#2101]
![bootstrap-select](https://user-images.githubusercontent.com/2701479/45557087-d060f900-b80a-11e8-8551-3c432404ab8d.gif)

As you can see in the gif, when using liveSearch, and clicking on an option, the highlighted option gets a tick as well. This is with bootstrap 4, Firefox and Chrome. 

EDIT: here's the live demo:

https://plnkr.co/edit/9Yi0QzLpu9uvcI17gnDZ?p=preview

Start a search and click on the second option. You'll see that the first option is also selected, even though it wasn't clicked.

**Comment by caseyjhol** [comment]
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/snapappointments/bootstrap-select/blob/master/CONTRIBUTING.md), please create a reduced test case via [Plunker](https://developer.snapappointments.com/bootstrap-select/playground/), [jsFiddle](https://jsfiddle.net/), [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/), and report back with your link, Bootstrap version, bootstrap-select version, and specific browser and OS details.

This seems like an issue that was fixed in v1.13.2 (#2027).

**Comment by jaredtaskin** [comment]
> Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/snapappointments/bootstrap-select/blob/master/CONTRIBUTING.md), please create a reduced test case via [Plunker](https://developer.snapappointments.com/bootstrap-select/playground/), [jsFiddle](https://jsfiddle.net/), [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/), and report back with your link, Bootstrap version, bootstrap-select version, and specific browser and OS details.
> 
> This seems like an issue that was fixed in v1.13.2 (#2027).

I have updated my post with a live demo. It is different from the issue you linked. Thanks!

**Comment by caseyjhol** [comment]
Looks like this was introduced in v1.13.2.

**Comment by jaredtaskin** [comment]
It appears that the first, highlighted option is not actually selected, it's just erroneously given a checkmark.

**Comment by caseyjhol** [comment]
I've pinpointed the problem. Should be fixed in the next release.

**Comment by caseyjhol** [comment]
Released in [v1.13.3](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.3)!
