### ISSUE TITLE
Pressing tab after focus causes javascript error

### ISSUE THREAD

**Issue by ronantreacy** [snapappointments/bootstrap-select#2110]
When tab is pressed after selecting an option in the dropdown list a javascript error is thrown: `Uncaught TypeError: Cannot read property 'findLis' of undefined`. This is caused by the `keydown` event on the button input.

The tab key works as expected, the next input field is focused, so the only problem is that an error is logged to the console.

Behaviour can be seen in this [live example](https://jsfiddle.net/nmrj8vqd/2/). Open console, select an item in dropdown, press tab key.

**Comment by caseyjhol** [comment]
It looks like you're removing the `dropdown-toggle` class, which is required (and why that error is being thrown).

**Comment by LordChengZ** [comment]
I used the class, but it doesn't work

`<select  class="form-control selectpicker dropdown-toggle"  data-live-search="true" multiple></select>`

**Comment by leafernandez** [comment]
Hi!

Same for me, it gives the error in the console even when adding the class `dropdown-toggle`.

The problem was already described also here: [https://github.com/snapappointments/bootstrap-select/issues/1085#issuecomment-388294598](https://github.com/snapappointments/bootstrap-select/issues/1085#issuecomment-388294598)

**Comment by kriit24** [comment]
Hi.

Same for me.

Uncaught TypeError: Cannot read property 'findLis' of undefined
    at HTMLButtonElement.keydown (bootstrap-select.js:2530)
    at HTMLDocument.dispatch (jquery.min.js:3)
    at HTMLDocument.r.handle (jquery.min.js:3)
