### ISSUE TITLE
data-hidden broken in v1.13.0

### ISSUE THREAD

**Issue by McNetic** [snapappointments/bootstrap-select#2140]
The 'hidden' attribute of the <option> tag should be handled as it is in a native select. That means: An option with the hidden attribute is not visible, unless it is selected (usually by also setting the selected attribute). 

I know of at least two applications of hidden options: The first (which could be implemented with bootstrap-select otherwise) is the display of a greyed out message for selects with no option selected. The second is a simple way to provide the selected value when generating the list programmatically by simply adding the option with the selected value as an additional, hidden option (in some templating languages, it is quite complicated to only add the selected attribute to the right option).

[A live example of both (with the corresponding native selects) is available](https://plnkr.co/edit/GRAoOkkgFpHsfYCapevY?p=preview).

**Comment by caseyjhol** [comment]
I can't find any reference in the HTML spec to `hidden` being a valid option attribute (http://w3c.github.io/html-reference/option.html#option). Can you link me to anything?

Setting `data-hidden="true"` should be a viable workaround, but it looks like that's been partially broken since v1.13.0 (it works in v1.12.4). https://plnkr.co/edit/F0VgmOD4yCPoHuWKIkPV?p=preview

bootstrap-select does have a built-in way of dealing with what you're trying to do with the first application: set the `title` attribute on the select.

**Comment by McNetic** [comment]
`hidden` is a global attribute: [https://w3c.github.io/html-reference/global-attributes.html](https://w3c.github.io/html-reference/global-attributes.html) and thus valid on all tags.

**Comment by caseyjhol** [comment]
Great - thanks! I'll get `data-hidden` working as it should, and then throw in `hidden` support as well, since it's the same functionality.

**Comment by caseyjhol** [comment]
Released in [v1.13.4](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.4)!
