### ISSUE TITLE
Optgroup selectAll bug

### ISSUE THREAD

**Issue by hisune** [snapappointments/bootstrap-select#2169]
- tested in: 1.13.5
- demo: https://jsfiddle.net/8dcx5y64/
![aabbc](https://user-images.githubusercontent.com/7941669/50682144-df351b00-1048-11e9-93b1-1bf36ad11e27.png)

**Comment by caseyjhol** [comment]
It's doing that because you're using a non-standard way of hiding options. bootstrap-select doesn't know those options are supposed to be hidden.

Can I ask why you're doing `style="display: none;"` on every disabled option? It'd probably be easier to just set `data-hide-disabled="true"` on the select element. Or if you don't want to do that for some reason, use the `hidden` attribute instead. We could check to see if the option has `style="display: none;"` set when generating the list, but it'd just be another thing to check for, and there are already cleaner alternatives. If you can make a case for why you need to be using `style="display: none;"`, I'll consider adding support for it.
