### ISSUE TITLE
Lazy render bootstrap-select

### ISSUE THREAD

**Issue by grosser** [snapappointments/bootstrap-select#2187]
Our pages were loading super slow when they had lots of big bootstrap-selects on them,
so I switched it to only actually go through all the work when the element is clicked.
This seems like a simple fix that could solve lots of the performance issues I saw here.

```js
  function convertToLiveSelect(select){
    return $(select)
      .addClass("selectpicker") // hide select and apply styles
      .selectpicker() // apply select picker
  }

  // user tabs into select (and will press down/space next)
  $(".lazy-selectpicker:not(.selectpicker)").one("focus", function(){
    convertToLiveSelect(this)
      .focus(); // focus new element instead
  });

  // user clicks on select
  $(".lazy-selectpicker:not(.selectpicker)").one("mousedown", function(e){
    e.preventDefault(); // do not open real select
    convertToLiveSelect(this)
      .next().click(); // trigger selectpicker
  });

  // multiselects look bad when not rendered
  $(".lazy-selectpicker[multiple]").unbind("mousedown").selectpicker();
```

**Comment by caseyjhol** [comment]
While this exact feature hasn't been added, offloading the initial data calculation via a setTimeout allows the button elements and the rest of the page to load quickly. For large selects, the time in which lazy rendering would really be of benefit, the delay in opening the menu would be too great in my opinion. If people are still running into issues, let me know and I can reopen this issue and address it in a future release. Otherwise, considering this released in [v1.13.6](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.6)!
