### ISSUE TITLE
Dependencies bootstrap < 3.4.1 / CVE-2019-8331

### ISSUE THREAD

**Issue by yafp** [snapappointments/bootstrap-select#2223]
The current version 1.13.2 has bootstrap >=3.0.0 as dependency according to package.json.

Maybe interesting https://nvd.nist.gov/vuln/detail/CVE-2019-8331

 Patched version of bootstrap: 3.4.1

**Comment by caseyjhol** [comment]
While there is an XSS vulnerability in versions before Bootstrap v3.4.1, that was only for popover and tooltip, which are unused by bootstrap-select. Bootstrap being a peer dependency gives us some more flexibility, but I'm inclined to keep it at >=3.0.0, since it does still work with versions earlier than v3.4.1, and it's possible somebody is using just dropdown.js.
