### ISSUE TITLE
Can't get :focus, :valid like form-control

### ISSUE THREAD

**Issue by rayhantr** [snapappointments/bootstrap-select#2249]
I am trying to give a floating label in the selectpicker. I tried the floating label in normal form-control select where I gave a `.form-control:focus + .form-control-placeholder,
.form-control:valid + .form-control-placeholder` did the work for me https://jsfiddle.net/sinDbad/jc7qfL1e/.
I did the same thing with selectpicker but I can't get the `:focus` and `:valid` to do work like form-control in selectpicker. After some work around I noticed that `.bootstrap-select:active` works with mouse click https://jsfiddle.net/sinDbad/nv0deugh/58/. I tried to do this with only css, but may be I need jQuery. Can I have some direction please. Thank you!

**Comment by caseyjhol** [comment]
Because the button is inside a div, it's not possible to do this with CSS only (as there isn't currently a working "parent" CSS selector). In addition, the focus shifts from the button to the menu after it's opened. Once there is a template option, in addition to a change so the focus doesn't shift, you could perhaps do this all with CSS (you'll want to modify the `createDropdown` function if you want to include `.form-control-placeholder` immediately after the button). Otherwise, this would be the best method for now:

```js
$('#selDepApt').on('shown.bs.select', function () {
    $('.bootstrap-select').addClass('focused');
});
  
$('#selDepApt').on('hide.bs.select', function () {
    $('.bootstrap-select').removeClass('focused');
});
```

```css
.focused + .form-control-placeholder {
    transform: translate(0, -1.1em);
    font-size: 70%;
    transition: 0.2s ease-in-out;
}
```

Or you could add the focused class directly to `.form-control-placeholder`.
