### ISSUE TITLE
weird formatting with bootstrap 4

### ISSUE THREAD

**Issue by seanVonDrake** [snapappointments/bootstrap-select#2278]
hello everybody, I am having issues using bootstrap-select with bootstrap 4; I am using the following versions:
`https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css
https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.10/dist/css/bootstrap-select.min.css
https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.10/dist/js/bootstrap-select.min.js`
here you can see a select without the selectpicker class (left) and the one with the selectpicker class (right), as you can see the right one is not properly styled, and I can't understand why:
![image](https://user-images.githubusercontent.com/11670332/57694417-ec43c580-764b-11e9-83ce-61e5870b9ded.png)
the HTML markup is:
`<select name="fatturati[id_cliente]" id="fatturati_id_cliente" class="form-control form-control-sm selectpicker" onchange="submit();" required data-live-search="true">
    <option value="">cliente</option>        <option value="15">Antonini Antonio</option>
        <option value="6">Caio Tizio</option>
        <option value="2">Cliente di Test</option>
    </select>`
thank you for any help!

**Comment by tiesont** [comment]
The left select actually seems (to me, at least) to be the incorrect item - that's not the styling I would expect from a small select. 

If, by "not properly styled", you're referring to the color difference, that's because Bootstrap 4's default button style (`btn-secondary`) is that medium grey color. You can get something closer to the Bootstrap `form-control` by overriding the defaults - I use something like this:

```js
$.fn.selectpicker.Constructor.DEFAULTS.style = 'btn-outline-light bg-white text-dark border';
```
