### ISSUE TITLE
Dropup becomes a dropdown upon search

### ISSUE THREAD

**Issue by imranion** [snapappointments/bootstrap-select#2320]
The issue I am experiencing is a select box dropup turning into a dropdown upon search. 

![bootstrap-select-dropupissue](https://user-images.githubusercontent.com/31263815/64000848-e2d26080-cb49-11e9-8516-09e92190615c.gif)

As the page the select box is on has other dynamic content, locking to dropup with data-dropup-auto="false" and the dropup class does not help - this particular dropbox needs to be a dropdown near the top of the page and a dropdown near the bottom.

This does not seem to be an issue on bootstrap 4.

Bootstrap-select v1.13.10
Bootstrap 3.4.1
JQuery 3.4.1
Both Chrome 76, Firefox 68 on Windows 10 64 bit.

[Test case (On 1920x1080 screen - position for the select box to dropdown may be different on other resolutions)](https://plnkr.co/edit/cmLyiYYRIjIiv9O2sh6F?p=preview)

**Comment by caseyjhol** [comment]
Released in [v1.13.13](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.13)!

**Comment by wout313** [comment]
Hey @caseyjhol,
Not sure if i should post it here or in a new issue since this already closed,
But i'm experiencing the same problem with my selectboxes changing dropup/dropdown after search. 
But now it is in the 1.14.0-beta2 version of the package.

I was wonderring if you could look into this as well.

If you need more information just let me know!

**Comment by NicolasCARPi** [comment]
@wout313 It's better if you open a new issue with **reproducible** test case and the code you use and all related information. Commenting on a closed issue will not get noticed.
