### ISSUE TITLE
Cannot create property 'guid' on string ':not(.bootstrap-select)

### ISSUE THREAD

**Issue by 1day2die** [snapappointments/bootstrap-select#2679]
Hello everyone,

when i fire bootstrap select up, i get the following error message

![image](https://user-images.githubusercontent.com/8725848/143395102-b0a4e682-30b8-4c73-a629-9e9103496822.png)

As well as this happening

![image](https://user-images.githubusercontent.com/8725848/143395140-28e0ea6e-dd62-416e-8b7a-2b51fda1b96e.png)

Couldnt find anything regarding this error.

The code is simple
![image](https://user-images.githubusercontent.com/8725848/143395216-6becb389-62e3-4df6-be2c-3b4f72017122.png)

I couldnt find anything related to that problem on the internet.
Maybe someone here knows whats up

Bootstrap: 4.6.1
JQuery: 3.6.0
bootstrap-select: 1.14

4. **Create an isolated and reproducible test case.** Create a reduced test
   case and include a link to a live example. Use [this Plunker debugging template](https://developer.snapappointments.com/bootstrap-select/playground/) to share your isolated test cases.

Im not able to do that :L

**Comment by NicolasCARPi** [comment]
> I couldnt find anything related to that problem on the internet.

Might want to improve your google-fu then ;)

https://stackoverflow.com/questions/52828241/uncaught-typeerror-cannot-create-property-guid-on-string

Try with the version from git but I believe it's an issue related to your environment and not the lib, so I'll close this issue but feel free to comment with your findings and I'll reopen if it turns out to be a bug in this lib.
